import emoji from "react-easy-emoji";

export const greetings = {
	name: "Sai Venkat R Banda",
	title: "Hi all, I am Sai",
	description:
		"A passionate and innovative Full Stack Web Developer with 2+ years experience of building and maintaing Web applications with Java / JavaScript / TypeScript / Angaular JS / Nodejs / Python / PostgresSQL / Flask and some other modern libraries and frameworks.",
	resumeLink: "https://cv.nivishree.ga",
};

export const openSource = {
	githubUserName: "vnkt996",
};

export const contact = {saivenkat.996@gmail.com};

export const socialLinks = {
	facebook: "https://www.facebook.com/saivenkat.996",
	instagram: "",
	github: "https://github.com/vnkt996",
	linkedin: "https://www.linkedin.com/in/sai-venkat/",
};

export const skillsSection = {
	title: "What I do",
	subTitle:
		"INNOVATIVE AND PASSIONATE FULL STACK DEVELOPER WHO WANTS TO EXPLORE EVERY TECH STACK",
	skills: [
		emoji(
			"⚡ Developed an end to end backend application using spring boot frame work"
		),
		emoji(
			"⚡ Professional experience in using Java, SQL."
		),
		emoji(
			"⚡ Worked on all phases of development from requirement gathering to deployment and maintainence."
		),
	],

	softwareSkills: [
		{
			skillName: "html-5",
			fontAwesomeClassname: "vscode-icons:file-type-html",
		},
		{
			skillName: "css3",
			fontAwesomeClassname: "vscode-icons:file-type-css",
		},
		{
			skillName: "sass",
			fontAwesomeClassname: "logos:sass",
		},
		{
			skillName: "JavaScript",
			fontAwesomeClassname: "logos:javascript",
		},
		{
			skillName: "TypeScript",
			fontAwesomeClassname: "logos:typescript-icon",
		},
		{
			skillName: "AngularJS",
			fontAwesomeClassname: "vscode-icons:file-type-angular",
		},
		{
			skillName: "VueJS",
			fontAwesomeClassname: "vscode-icons:file-type-vue",
		},
		{
			skillName: "nodejs",
			fontAwesomeClassname: "logos:nodejs-icon",
		},
		{
			skillName: "npm",
			fontAwesomeClassname: "vscode-icons:file-type-npm",
		},
		{
			skillName: "sql-database",
			fontAwesomeClassname: "vscode-icons:file-type-sql",
		},
		{
			skillName: "aws",
			fontAwesomeClassname: "logos:aws",
		},
		{
			skillName: "firebase",
			fontAwesomeClassname: "logos:firebase",
		},
		{
			skillName: "python",
			fontAwesomeClassname: "logos:python",
		},
		{
			skillName: "git",
			fontAwesomeClassname: "logos:git-icon",
		},
		{
			skillName: "docker",
			fontAwesomeClassname: "logos:docker-icon",
		},
		{
			skillName: "Flask",
			fontAwesomeClassname: "logos:flask",
		},
		{
			skillName: "Jenkins",
			fontAwesomeClassname: "logos:jenkins",
		},
		{
			skillName: "JSON",
			fontAwesomeClassname: "logos:json",
		},
		{
			skillName: "Drupal",
			fontAwesomeClassname: "logos:drupal",
		},
		{
			skillName: "XML",
			fontAwesomeClassname: "vscode-icons:file-type-xml",
		},
	],
};

export const SkillBars = [

];

export const educationInfo = [
	{
		schoolName: "Virginia Tech",
		subHeader: "Master of Science in Computer Science",
		duration: "August 2021 - December 2022",
		desc: "GPA: 3.95/4",
		descBullets: [
			"Grader",
			"Specializatin in Software Engineering",
			"Relevant Course work: Software Engineering, Software Project Management, Web Application Development, Data Structures and Algorithms, Theory of Algorithms, Data Analytics"
		],
	},
	{
		schoolName: "Birla Institute of Science and Technology - Pilani",
		subHeader: "B.E.(hons) Computer Science",
		duration: "August 2015 - May 2019",
		desc: "GPA: 8.17/10",
		descBullets: [
			"Relevant Course Work: Computer Architecture, Computer Networks, Operating Systems, Soft computing techniques, Digital Communication, C++, Data Structures and Algorithms, Python",
		],
	},
];

export const experience = [
	{
		role: "Software Engineer",
		company: "OYO",
		companylogo: "/img/icons/common/vtf.png",
		date: "June 2019 – May 2021",
		descBullets: ["Engineered Promotion Service APIs for coupon creation, enabling 16 times more features.",      
		"Implemented Pricing Service (in a team of 2), improving website loading time by 70%.", 
		"Fixed a scheduling bug by using Apache Kafka messaging queues to keep track of move out tasks, reducing
on-call issues occurring from scheduling tasks by 20%.", 
		"On demand from customers, developed feature to find a property by metro line and distance, saving customers
2 min per each search.",
		"Designed and implemented invoice generation task, which reduced the number of invoices generated by more
than 50%, appreciably improving customer experience."],
	},
	{
		role: "Software Development Intern",
		company: "Amazon",
		companylogo: "/img/icons/common/philips.png",
		date: "Jan 2019 – May 2019",
		descBullets: [
			"Developed and deployed an automatic report generation tool for errors, exceptions, and SLA breaches using Java with DynamoDB as database and deployed in AWS.",
			"This project saves around 4 hours for on-calls every week, reducing their workload by 10%.",
		],
	},
	{
		role: "Software Development Intern",
		company: "United HealthGroup",
		companylogo: "/img/icons/common/philips.png",
		date: "May 2018 – July 2018",
		descBullets: ["Developed a backend APIs for the Optum Data Lake team using NodeJS, enabling developers, managers, and executives to monitor insurance metrics in real-time instead of once a day",
		"Collaborated with senior developers on reducing the load on the backend servers and elastic search servers by implementing cache, which reduced the number of pods by more than 50%.",],
	},
];

export const projects = [
	{
		name: "Wearable Inspection and Report Management System (WIRMS)",
		desc: "UX designing for an Augmented Reality application developed in conjunction with the Virginia Department of Transportation (VDOT) that provides bridge inspectors with tools for developing and generating on-site bridge inspection reports. ",
		link: "https://github.com/nivishree",
	},
	{
		name: "Online Bookstore Website Development",
		desc: "Independently developed a user interactive “Online Bookstore” where the order can be booked, and payments can be done shortly along with getting all the required details regarding each book",
		link: "https://github.com/nivishree",
	},
	{
		name: "Intelligent Robot for Blind ",
		desc: "Collaborated a team of 3 and designed an intelligent path guiding robot interfaced with camera. Modelled an image classifier using Convolutional Neural Networks with an accuracy greater than 90%",
		link: "https://github.com/nivishree",
	},
	{
		name: "Food Delivery Application",
		desc: "Built an android application that connects passengers with several restaurants on the Indian Rail network. It completes an entire fulfillment cycle right from the point of ordering to Delivery, Customer feedback and Reconciliation",
		link: "https://github.com/nivishree",
	},
	{
		name: "Case Study: Nursing Dashboard",
		desc: "Designed a dashboard that can be used for Intensive care unit(ICU) which notifies which patient needs emergency timely care and warns the nurses in duty",
		link: "https://github.com/nivishree",
	},
];

